import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PartnerProvider } from "@/context/PartnerContext";
import { OrderProvider } from "@/context/OrderContext";
import { AssignmentProvider } from "@/context/AssignmentContext";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PartnerProvider>
          <OrderProvider>
            <Sidebar />
            <div className="ml-64">
            <AssignmentProvider>{children}</AssignmentProvider>
            </div>
          </OrderProvider>
        </PartnerProvider>
      </body>
    </html>
  );
}
